export const EVENTS = {
	ANIMAL_SPECIES: 'ANIMAL_SPECIES',
	FEED: 'FEED',
	FEED_RECEIPT: 'FEED_RECEIPT',
	FEED_SEGMENT: 'FEED_SEGMENT',
	FEED_TITLE: 'FEED_TITLE',
	INGREDIENT: 'INGREDIENT',
	INGREDIENT_QUALITY: 'INGREDIENT_QUALITY',
	MARKET_DEMAND: 'MARKET_DEMAND',
	PRODUCTION: 'PRODUCTION',
	PROVIDER: 'PROVIDER',
	UKRAINE_REGION: 'UKRAINE_REGION',

	TRAIN_PREDICTION_MODEL: 'TRAIN_PREDICTION_MODEL'
} as const;